# Site
name: "Anicode"
title: "Anicode - grab the latest and amazing programming related stuffs on the web!"
description: "Top Programming and coding related stuffs on the web, that makes developers task easy!"
logo: 'assets/img/logo.png'
favicon: 'assets/img/logo.png'
baseurl: http://anicode.in
google_analytics: 'UA-179390051-1'
disqus: 'anicode'
mailchimp-list: 'https://anicode.us2.list-manage.com/subscribe/post?u=24d932cf7b5f5f8e2ebc2c8df&amp;id=92e5280a70'
include: ["_pages"]
permalink: /:title/




# Authors
authors:
  anicode:
    name: Abhi
    display_name: Abhi
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: abhiprojectz01@gmail.com
    web: http://anicode.in
    twitter: https://twitter.com/abhiprojectz
    description: "Author of Anicode.in. Passionate developer , designer and android core developer creating problem focused libraries and projects."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-3532869867982273"

# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [LICENSE.txt, README.md, Gemfile, Gemfile.lock]
